In [1]:
import numpy as np

In [15]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45], dtype=np.uint16)

In [ ]:
# print('shape: ',month_results.shape)
# print('len: ', len(month_results))
# print('ndim: ', month_results.ndim)
# print('dtype: ', month_results.dtype)

new = month_results.reshape(4,7)
print(new)

shape:  (28,)
len:  28
ndim:  1
dtype:  uint16
[[ 56 100  33   0  45  45  46]
 [ 34  89 180  60  45  45  44]
 [ 46  45   0   0  15  90 301]
 [197  20  60  45  45  42  45]]
